"""add ai_feedbacks

Revision ID: 19264cd7d89b
Revises: b8e430575fb7
Create Date: 2026-04-10 18:55:49.454468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19264cd7d89b'
down_revision: Union[str, None] = 'b8e430575fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating_score', sa.Integer(), nullable=False),
    sa.Column('feedback_tags', sa.JSON(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('ai_version', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedbacks_content_id'), 'ai_feedbacks', ['content_id'], unique=False)
    op.create_index(op.f('ix_ai_feedbacks_id'), 'ai_feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_feedbacks_id'), table_name='ai_feedbacks')
    op.drop_index(op.f('ix_ai_feedbacks_content_id'), table_name='ai_feedbacks')
    op.drop_table('ai_feedbacks')
    # ### end Alembic commands ###
