"""add ai_feedbacks

Revision ID: 19264cd7d89b
Revises: b8e430575fb7
Create Date: 2026-04-10 18:55:49.454468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19264cd7d89b'
down_revision: Union[str, None] = 'b8e430575fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_feedbacks', sa.Column('metadata_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_feedbacks', 'metadata_json')
    # ### end Alembic commands ###
