"""Add difficulty to questions

Revision ID: 194558da7986
Revises: 7c3e1f9d5a2b
Create Date: 2026-03-30 09:27:45.266737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194558da7986'
down_revision: Union[str, None] = '7c3e1f9d5a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('difficulty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'difficulty')
    # ### end Alembic commands ###
