"""Add skill metrics

Revision ID: 96adaa7179bf
Revises: cc281bdd0a68
Create Date: 2026-04-11 01:09:32.863344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96adaa7179bf'
down_revision: Union[str, None] = 'cc281bdd0a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competency_analysis', sa.Column('skill_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competency_analysis', 'skill_metrics')
    # ### end Alembic commands ###
