"""add contest management fields

Revision ID: a2b3c4d5e6f8
Revises: 3f4a1b2c9d10
Create Date: 2026-04-17 19:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = 'a2b3c4d5e6f8'
down_revision: Union[str, None] = '3f4a1b2c9d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.add_column('contests', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'is_active')
    op.drop_column('contests', 'image_url')
    # ### end Alembic commands ###
